sudo:
  required

dist:
  trusty

services:
  - elasticsearch

addons:
  postgresql: "9.4"
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.3
  # - 3.4
  - 3.5
  - 3.6

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

before_script:
  - sleep 10

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: SLwTXmKG7RIHrn+/HiShiIXdSO1xTNNy0iDKAlErC2tfb0HhkwcjQivW0RxW1eG20VJw2oLyLNS0xCOBVoaEbk9xJu/OA758qTgBCGpTnBLcpL9XI3c2/WQB2CUbbFSFedeQPOsDXE+G7q570ttIjKfcM9n2NHLiG8zK1gk1Mj+zcQ1muELnXfSvb+6tw2rxpyEMVEgToqfwH1J+13YMAbCym+Jr/lFnOZ8NS9nBenAQPNVqnZvy8M8aIl43gw5CFwjlNItnGrrTx9NNbm1q6KAVIBvB62z8ELjIotDV7sWHLnRMExzoIbr3l27rCcub8q3PV6tVd38vhHDjWJZs/COKbvcYm5mWe7orDzJtUPHp97GW1e0/I0QLED/SPPof/hbaDrlUn6MATqUg4zskvDWhymoZCBnf1EiQL9zE3ruTtSGojVllHZ8LonaOnPTyxi/e7sZuIEacjNeDlf671Wqd7qb7ll98ip8r6zhgXV+jAj6o8fsfivzjqxkNfKSA0N1B6GfEj08ZW6UNpZqtvNFJ+BVBtEqZ+ocXTUD97/N1e707K9vAVqjeY91ehapG4piRr0z0oq2fTukV9RnysntodVTT+5YG9IsWwpOGiKSMlYVAhUtQFrOo6SVGv/h5HMThaBlJsJWZ/MIxy3xlEjOJ2SZ+et6at+KbO/h1OzE=
