sudo:
  required

dist:
  trusty

addons:
  postgresql: "9.4"
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

